### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by basrulyandri** [rollo-hai/hai#3]
migration error karena urutan pembuatan harusnya dimulai dari roles, permissions, permission_role dan users

**Comment by ajatdarojat45** [comment]
mohon dikeluarkan dulu migration craete_user_tabel dan create_password_reset_table. setelah itu lakukan migrate. dan pindahkan satu-satu migration yang kita keluarkan directory semula dan lakukan migrate. ulangi untuk migration selanjutnya.

**Comment by rollo-hai** [comment]
Saya sudah tambahin ada beberapa perubahan supaya menyesuaikan gentelella dan RBAC yang terbaru. 

Tapi baru saya push ke branch Basrul. Untuk lebih lengkapnya lihat readme di branch basrul

@ajatdarojat45 @suryana22 @ginanjar

**Comment by ajatdarojat45** [comment]
siap pak @basrulyandri

**Comment by Ginanjar** [comment]
Maaf, spertinya salah email untuk Ginanjar
